default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: admin
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: myapp_development
